version: "3.9"
services:
  testecharlinho-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/testecharlinho-debug:${TAG}
    ports:
      - ${DEBUG_SSH_PORT}:${DEBUG_SSH_PORT}

  testecharlinho:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}/testecharlinho:${TAG}
